WEBAPICIp/Controllers/ListClientesControllerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntity;
using dummiesServiciosTienda.Models;

namespace dummiesServiciosTienda.Controllers
{
    public class ListClientesController : Controller
    {
        //
        // GET: /ListClientes/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /ListClientes/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /ListClientes/Create

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult UpdateClientes()
        {
            return View();
        }


        //
        // POST: /ListClientes/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                string Dnia = collection["Numero1"];
                string DNIB = collection["Numero2"];
                ClienteResource proce = new ClienteResource();
                proce = ProcesarClientes.GetCliente(DNIB);

                return View(proce);
                //return Json(proce, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ListClientes/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /ListClientes/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ListClientes/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /ListClientes/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WEBAPICIp/Views/ListClientes/Create.cshtml
@model dummiesServiciosTienda.Models.ClienteResource

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <title>@ViewBag.Title</title>
    @System.Web.Optimization.Styles.Render("~/Content/css")
    @System.Web.Optimization.Scripts.Render("~/bundles/modernizr")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryuiProcesosClientes")
</head>

<body>
    <div ng-app="mainApp" ng-controller="studentController">
        <p>Name:<input type="text" ng-model="name" /></p>
        @{  if (Model != null)
          {
            <table>
                <tr><td>ApellidoPaterno</td><td>ApellidoMaterno</td><td>AceptaPolitica</td><td>CodigoAfiliacion</td><td>Email</td><td>FechaModificacion</td><td>Mensaje</td></tr>
                <tr><td>@Model.Cliente.ApellidoPaterno</td><td>@Model.Cliente.ApellidoMaterno</td><td>@Model.Cliente.AceptaPolitica</td><td>@Model.Cliente.CodigoAfiliacion</td><td>@Model.Cliente.Email</td><td>@Model.Cliente.FechaModificacion</td><td>@Model.Mensaje</td></tr>
            </table>

          }
          else
          {
            <div>NO hay registro valido</div>

          }

        }

       



        Enter first name: <input type="text" ng-model="student.firstName"><br><br>
        Enter last name: <input type="text" ng-model="student.lastName"><br>

        <p ng-bind="mainApp"></p> <p ng-bind="mainApp"></p>
        <h1 ng-bind="mainApp"></h1>
        <label ng-bind="mainApp"></label>
        <h2 ng-bind="mainApp" style="color:ActiveCaption"></h2>

        <p>My first expression: {{ 5 + 5 }}</p>
        <br>

        You are entering: {{student.fullName()}}
    </div>

    <script>
        var mainApp = angular.module("mainApp", []);

        mainApp.controller('studentController', function ($scope) {
            $scope.student = {
                firstName: "Mahesh",
                lastName: "Parashar",

                fullName: function () {
                    var studentObject;
                    studentObject = $scope.student;
                    return studentObject.firstName + " " + studentObject.lastName;
                }
            };
        });

  

    </script>




   
    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAngular")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAngularmin")
   
</body>
</html>

WEBAPICIp/Views/ListClientes/Index.cshtml
<!DOCTYPE html>

<html data-ng-app="angularapp">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
   
@section scripts{
    @System.Web.Optimization.Styles.Render("~/Content/css")
    @System.Web.Optimization.Scripts.Render("~/bundles/modernizr")
    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAngular")


    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryuiProcesosClientes")

   
        
        }

  


</head>
@*<body data-ng-init="Customer=[{name:'zarmir',city:'Lima Peru'},{name:'Cristian',city:'Ica'},{name:'Mendel',city:'USA'},{name:'Munuela',city:'Vado'},{name:'muñeca',city:'Itali'}]">*@
<body>
    <div data-ng-controller="ClientesControllers">
        <p>{{6-8}}</p>
        <ul>
            <li data-ng-repeat="salida in Customer">{{salida.name}}</li>
        </ul>
        <input type="text" data-ng-model="Modelo1" />
    </div>

    @using (Html.BeginForm("Create", "ListClientes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

    }
    @{

        if (Request.ContentLength != 0)
        {
            var Numeroa = Request["Numero1"].ToString();
            var numerob = Request["Numero2"].ToString();
            var resultado = double.Parse(Numeroa) + double.Parse(numerob);
            <h4>@resultado</h4>
        }


    }


</body>
</html>

WEBAPICIp/Views/ListClientes/UpdateClientes.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateClientes</title>
    @System.Web.Optimization.Styles.Render("~/Content/css")
    @System.Web.Optimization.Scripts.Render("~/bundles/modernizr")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAngular")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAngularmin")

</head>
<body>
    <div ng-app="APP_" ng-controller="UpdateClientes" >
        <input  type="text" ng-model="Nombre"/>
        <input type="text"  ng-model="Apellidos"/>
        Full Name {{ Nombre +"  "+  Apellidos }}
        
    </div>



    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryuiProcesosClientes")
</body>
</html>